### PR TITLE
Dev derive

### PR DESCRIPTION
**Pull request by donaldcampbelljr**
- refactor basic and pipestat examples to use sample modifiers
- add advanced example to be used for Looper testing

### CODE REVIEW

**Comment by donaldcampbelljr** [comment]
This PR is in tandem with:
https://github.com/pepkit/looper/pull/472

**Comment by nsheff** [comment]
Why do we want the basic pipeline to use sample modifiers? I think we should *not* do that. This is a step backwards. The basic pipeline should be the simplest possible pipeline.

**Comment by nsheff** [comment]
The advanced one looks good, though -- maybe just come up with a different name rather than 'advanced' that's more descriptive? Since we might have more than one 'advanced' pipeline?

And: add it to the README.md

**Review by nsheff — APPROVED** [review]

**Comment by donaldcampbelljr** [comment]
I added a minimal example. Refactored basic to intermediate.

**Pull request merged**
